Pricing per user
charge-angels/ca-ev-server pull request #16
Opened 2022-10-25 13:29 UTC by Skyriixxx

2022-10-25 13:38 UTC, LucasBrazi06 requested changes
Check my comments

2022-10-25 13:38 UTC, LucasBrazi06 commented on src/authorization/AuthorizationsDefinition.ts
> +        resource: Entity.USER, action: [Action.READ, Action.MAINTAIN_PRICING_DEFINITIONS],
MAINTAIN_PRICING_DEFINITIONS should be with UPDATE and not READ.

2022-10-25 14:16 UTC, Skyriixxx commented on src/authorization/AuthorizationsDefinition.ts
> +        resource: Entity.USER, action: [Action.READ, Action.MAINTAIN_PRICING_DEFINITIONS],
Done

2022-10-26 15:28 UTC, LucasBrazi06 approved these changes
Looks good!

2022-10-27 08:39 UTC, merged