Step2-display-grid-monitoring-for-integration-setting (Server)
charge-angels/ca-ev-server pull request #51
Opened 2022-11-21 20:19 UTC by Skyriixxx

2022-11-21 21:30 UTC, LucasBrazi06 requested changes
Check my comments

2022-11-21 21:30 UTC, LucasBrazi06 commented on src/assets/server/rest/v1/schemas/setting/setting-grid-monitoring-set.json
> +                      "normalConsumption": {
I asked Liam to push the GridMonitoring settings (GridMonitoring.ts).
Check and align all levels.
You should have contacted Liam for knowing the setting interface!
![image](https://user-images.githubusercontent.com/25266945/203161776-8c08428d-c678-4096-927a-07f5d677d39d.png)
Fix the naming in the front also.

2022-11-22 09:39 UTC, Skyriixxx commented on src/assets/server/rest/v1/schemas/setting/setting-grid-monitoring-set.json
> +                      "normalConsumption": {
Done

2022-11-22 10:20 UTC, LucasBrazi06 approved these changes
GUT

2022-11-22 10:21 UTC, merged